[package]
name = "key-derivation"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.3"
rand = "0.8.5"
getrandom = { version = "0.2", optional = true }
num-bigint = "0.4.6"
num-traits = "0.2.19"

[features]
default = []
wasm = ["getrandom/js"]
